name: Draft PDF
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # Specify the correct path to your paper
          paper-path: paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # Path to the output PDF
          path: paper/paper.pdf
          
